# Generated by Django 3.2 on 2021-04-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
                ('views', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
